<a href="https://colab.research.google.com/github/adhamahmed2021/Ahmed-Data-Science/blob/main/Adham_Ahmed_Stats_2023_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stats Notebook Lab #3

### Loops

In [206]:
for i in range(100): #ask python to print the first 100 numbers
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [207]:
for i in range(5,8):   #ask python to print every number from 5-8 (Question: how come it prints 5 but not 8?)

    print(i)

5
6
7


In [208]:
for i in range(3):
    print( "Test Number: " , i )      #ask python to print the first 3 numbers with certain text in front of it

Test Number:  0
Test Number:  1
Test Number:  2


### Functions

In [209]:
def square(x):    #square(a number, x) is defined by the code for squaring a number
    return x**2

In [210]:
square(5)   #demonstrates function

25

In [211]:
square(square(2)) #squares 2 (= 4) then squares 4

16

In [212]:
square(square(square(2)))  #squares 2 (= 4) then squares 4 (= 16) then squares 16


256

In [213]:
square(123456)

15241383936

In [214]:
square(square(5))  #squares 5 (= 25) then squares 25

625

In [215]:
def add_two(x):      #function to add 2 to a number,x
    return x+2

In [216]:
add_two(5)     #demonstrates function

7

In [217]:
square(add_two(5))   #uses both functions to add 2 to 5 and square that number ((5+2)^2)

49

### Logical Branching

In [218]:
choice = "apple" #one equal is an assignment operator

In [219]:
if choice == "apple":  #two equal signs means a test of an operation or function

    print("You choose apples.")

else:                      #tells python that if it doesn't show one phrase, show the other
    
    print("You did not choose apples.")

You choose apples.


In [220]:
choice = "orange"

In [221]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You did not choose apples.


In [222]:
choice = "apple"

In [223]:
if choice == "apple":

    print("You choose apples.")
    print("Thank you, shop again!")

elif choice == "orange":          #elif means "else if", an alternative to the first choice

    print("You choose oranges.")
    print("Thank you, shop again!")

else:
    
    print("You did not choose apples or oranges.")
    print("Thank you, shop again!")

You choose apples.
Thank you, shop again!


### User Input

In [224]:
choice = input("Please enter your choice (i.e. apple): ") #input allows the user to type in a text box

Please enter your choice (i.e. apple): oranges


In [225]:
choice #displays what the user typed

'oranges'

In [226]:
if choice == "apple":

    print("You choose apples.")

elif choice == "oranges":

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.") #evaluates what the user typed and decided if it was under "if" or "elif", or neither

You choose oranges.


#### Coins

In [227]:
import numpy as np

In [228]:
np.random.random()   #generate random number between 0 and 1

0.2936772064232126

In [229]:
np.random.random() > 0.5   #if the number generated is greater than 0.5, the output is true

True

In [230]:
def flip_coin():         #heads vs tails function
    if np.random.random() > 0.5:
        print("Heads")         #if value is greater than 0.5, show heads
    else:
        print("Tails")         #if value is less than 0.5, show tails

In [231]:
flip_coin()     #ask python to generate number between 0 and 1 and display assigned output depending on value

Tails


### Graphics Output

In [232]:
from IPython.core.display import display, HTML #import HTML in python

In [233]:
display(HTML('<h1>Hello, world!</h1>'))    #how to display text from a code cell

In [234]:
def coin():          # function coin() is defined by a command asking python to choose randomly between the first 2 numbers
  return np.random.randint(2)     

In [235]:
coin()    #running np.random.randint(2) under its function name

1

In [236]:
display(HTML('<img src="https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg">'))  #shows image using HTML

In [237]:
heads = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg'   #defines head and tails variables
tails = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-back.jpg'

In [238]:
def show_img(img):          #defines funtion to display either heads or tail image
  display(HTML('<img src=' + img + '>'))

In [239]:
show_img(heads)   #show heads image

In [240]:
show_img(tails)       #show tails image

In [241]:
def flip_coin():     #define coin flip function

    if coin():            #tells python when to show heads
        show_img(heads)        
    else:                 #tells python that if it doesn't show heads, show tails
        show_img(tails)

In [242]:
flip_coin()     #actual coin flip

In [243]:
for i in range(5):
    flip_coin()           #flip coin 5 times

In [244]:
#@title Coin Flip

if coin():

  show_img(heads)

else:

  show_img(tails)

### Cards

In [245]:
def shuffle(x):
    for i in range(len(x)-1,0,-1):
        j = np.random.randint(0,i+1)
        x[i],x[j] = x[j],x[i]
        # print(j,x)
    return x

In [246]:
a = np.arange(52) #shows the first 52 numbers

In [247]:
shuffle(a) #shuffles the first 52 numbers

array([34, 14,  0, 49, 42, 44,  7, 31, 50, 26, 30, 37, 40, 16, 51, 25, 36,
       33, 24,  3,  5,  9, 38, 20, 27, 28,  1, 21, 48, 46, 13,  6,  4, 47,
       12, 41, 43, 23, 17,  2, 10, 19,  8, 32, 18, 29, 22, 45, 35, 15, 39,
       11])

In [248]:
np.random.permutation(52) #function to directly get the first 52 numbers and shuffle them

array([18, 50,  4, 10, 31, 23, 30,  9, 46, 25, 12, 42,  1, 26,  6, 20, 37,
       16,  2, 47, 51,  5, 14, 40, 44, 28, 29, 22, 39, 49, 36, 11, 38, 17,
       48, 32, 35,  8, 13, 15,  0, 43, 27, 41, 21,  3,  7, 24, 33, 45, 19,
       34])

### Speed Test

In [249]:
%%timeit   
shuffle(a) #measures how long the cell took to execute the command

176 µs ± 8.12 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [250]:
%%timeit
np.random.permutation(52)

3.34 µs ± 134 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [251]:
import numpy as np

In [252]:
np.random.permutation(52)

array([ 0, 38, 48, 26, 39, 12, 16, 37, 51, 15, 36, 30, 11,  5, 22, 17, 14,
       32, 21, 42, 47,  9, 46,  2,  7, 40, 34, 50,  1, 43, 44, 41, 31, 29,
       20, 27, 45,  3, 19, 18, 35,  8,  6, 25, 24, 13, 28, 10, 23, 49, 33,
        4])

In [253]:
cards = np.random.permutation(52) #variable defined by the function

In [254]:
cards #displays function

array([32, 10, 31, 37, 27, 15, 50, 13, 36, 51, 47, 28,  0, 18, 35, 44,  6,
       33, 23, 46, 42, 38,  7, 25, 48, 12, 43,  2, 14, 16, 24, 39, 22, 41,
       49,  8, 40, 11, 34,  5, 19, 45,  3,  4, 21, 30, 20, 26, 17,  1, 29,
        9])

In [255]:
cards[0] #shows first number in array

32

In [256]:
cards[1] #shows second number in array

10

In [257]:
cards[2]#shows third number in array

31

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [258]:
np.arange(52).reshape(4,13) #reshapes the list of numbers into 4 rows by 13 columns

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [259]:
np.arange(52).reshape(4,13)%13  #modulo operator

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [260]:
np.arange(52).reshape(4,13)//13   #2 forward slashes means floor division

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [261]:
suits = ['Clubs','Spades','Hearts','Diamonds'] #4 different card suits
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King'] #13 different card names

In [262]:
def card_name(card_number):
    
    suit = card_number//13 #perform floor division for card suits
    name = card_number%13 #use modulo operator for card names

    return names[name] + " of " + suits[suit] #output is "____ of ____"

In [263]:
card_name(0) #demonstrates function for first card

'Ace of Clubs'

In [264]:
card_name(51) #demonstates function for 52nd card

'King of Diamonds'

In [265]:
cards = np.random.permutation(52) #new variable using random shuffling of 52 cards

In [266]:
top_of_deck         = card_name(cards[0]) #calls first card in deck by card_name function
second_card_in_deck = card_name(cards[1])  #second card
last_card_in_deck   = card_name(cards[-1]) # -1 is another way of saying 51, last card in deck

In [267]:
top_of_deck, second_card_in_deck, last_card_in_deck #output of commannd

('Queen of Clubs', 'Four of Hearts', 'Nine of Hearts')

In [268]:
for i in range(5):
    print(card_name(cards[i]))  #python gives the first 5 cards from the shuffled deck

Queen of Clubs
Four of Hearts
Eight of Diamonds
Ten of Hearts
Three of Clubs


In [269]:
for i in range(15):
    print(card_name(cards[i]))  #python gives the first 15 cards from the shuffled deck

Queen of Clubs
Four of Hearts
Eight of Diamonds
Ten of Hearts
Three of Clubs
Two of Diamonds
Three of Spades
Eight of Spades
Ace of Spades
Ace of Hearts
Six of Hearts
Six of Spades
Jack of Spades
Ace of Diamonds
Three of Hearts


https://www.improvemagic.com/all-playing-cards-names-with-pictures/

In [270]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/" #url for images of playing cards
card_url_tail = ".png"

In [271]:
suit = ['k','p','s','l']   #4 different suits
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k'] #13 different cards

In [272]:
i = np.random.randint(4) #give a random number up to 4
j = np.random.randint(13)  #give a random number up to 13

In [273]:
i,j #give both numbers as a coordinate

(3, 3)

In [274]:
suit[i]  #give the value i that python genereated

'l'

In [275]:
card[j]   #give the value j that python genereated

'4'

In [276]:
from IPython.core.display import display, HTML   #import HTML in python

In [277]:
def show_img(img):                #defines funtion to display card image based on randomly generated card
  display(HTML('<img src=' + img + '>'))

In [278]:
img = card_url_head + suit[i] + card[j] + card_url_tail  #variable for card image

In [279]:
show_img(img)  #displays ace of diamonds, the random card generated by i and j

In [280]:
def card_image(card_number):
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j] #output is the coordinate of a the card in a 13x4 table

In [281]:
card_image(3) #displays coordinates of 4th card

'k4'

In [282]:
img = card_url_head + card_image(3) + card_url_tail  #variable for card image

In [283]:
show_img(img) #displays card defined by coordinates "k4"

In [284]:
for i in range(52):
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)     #displays all 52 cards using img variable